ASoC: rk312x: Fix missing prototypes
sound/soc/codecs/rk312x_codec.c:604:5: error: no previous prototype for rk312x_codec_mute_dac [-Werror=missing-prototypes]
sound/soc/codecs/rk312x_codec.c:2412:6: error: no previous prototype for rk312x_platform_shutdown [-Werror=missing-prototypes]

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I5faa117a8fb6a803bfeffc5c20473e362f4f7ed9