input: touchscreen: parade: Fix missing prototypes
drivers/input/touchscreen/parade/pt_core.c:10623:5: error: no previous prototype for function '_pt_request_pip2_enter_bl' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:10872:5: error: no previous prototype for function '_pt_pip2_file_open' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:10920:5: error: no previous prototype for function '_pt_pip2_file_close' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:10968:5: error: no previous prototype for function '_pt_pip2_file_erase' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:11039:5: error: no previous prototype for function '_pt_pip2_file_read' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:11081:5: error: no previous prototype for function '_pt_read_us_file' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:11174:5: error: no previous prototype for function '_pt_request_pip2_bin_hdr' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:11312:5: error: no previous prototype for function '_pt_pip2_file_get_stats' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:11381:5: error: no previous prototype for function '_pt_pip2_file_seek_offset' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:11436:5: error: no previous prototype for function '_pt_pip2_file_crc' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:11484:5: error: no previous prototype for function 'pt_pip2_ping_test' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:611:6: error: no previous prototype for function 'pt_toggle_err_gpio' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:634:6: error: no previous prototype for function '_pt_request_toggle_err_gpio' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:6667:5: error: no previous prototype for function '_pt_request_active_pip_protocol' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:8465:13: error: no previous prototype for function 'pt_irq' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:9064:5: error: no previous prototype for function 'pt_pip2_exit_bl_' [-Werror,-Wmissing-prototypes]
drivers/input/touchscreen/parade/pt_core.c:9201:5: error: no previous prototype for function 'pt_pip2_exit_bl' [-Werror,-Wmissing-prototypes]

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: Ic932fcb8acec2084d36812ac82d6a877ff5a7ca7