input: sensors: gyro: ewtsa: Fix missing prototypes
drivers/input/sensors/gyro/ewtsa.c:281:6: error: no previous prototype for function 'gyro_dev_reset' [-Werror,-Wmissing-prototypes]

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I95932a5cfbb38cd0f5019d965accfd3d07f79000