clk: rockchip: Fix missing rkclk_cpuclk_div_setting prototype for rk3128
drivers/clk/rockchip/clk-rk3128.c:566:6: error: no previous prototype for rkclk_cpuclk_div_setting [-Werror=missing-prototypes]

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I4f6407d9a09085d44de7a40e409b580256f99733