cpufreq: interactive: Fix missing prototypes
drivers/cpufreq/cpufreq_interactive.c:1372:5: error: no previous prototype for function 'cpufreq_interactive_init' [-Werror,-Wmissing-prototypes]
drivers/cpufreq/cpufreq_interactive.c:1463:6: error: no previous prototype for function 'cpufreq_interactive_exit' [-Werror,-Wmissing-prototypes]
drivers/cpufreq/cpufreq_interactive.c:1498:5: error: no previous prototype for function 'cpufreq_interactive_start' [-Werror,-Wmissing-prototypes]
drivers/cpufreq/cpufreq_interactive.c:1525:6: error: no previous prototype for function 'cpufreq_interactive_stop' [-Werror,-Wmissing-prototypes]
drivers/cpufreq/cpufreq_interactive.c:1543:6: error: no previous prototype for function 'cpufreq_interactive_limits' [-Werror,-Wmissing-prototypes]

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I83452d8e7acb41ff4a33a0f9c261208e72c8dad9