video: rockchip: mpp: Fix missing prototypes
drivers/video/rockchip/mpp/hack/mpp_rkvdec2_hack_rk3568.c:677:6: error: no previous prototype for function 'rkvdec2_3568_hack_data_setup' [-Werror,-Wmissing-prototypes]
drivers/video/rockchip/mpp/hack/mpp_rkvdec2_hack_rk3568.c:703:6: error: no previous prototype for function 'rkvdec2_3568_hack_fix' [-Werror,-Wmissing-prototypes]
drivers/video/rockchip/mpp/hack/mpp_rkvdec2_link_hack_rk3568.c:184:6: error: no previous prototype for function 'rkvdec2_3568_hack_fix_link' [-Werror,-Wmissing-prototypes]
drivers/video/rockchip/mpp/hack/mpp_rkvdec2_link_hack_rk3568.c:189:6: error: no previous prototype for function 'rkvdec2_link_hack_data_setup' [-Werror,-Wmissing-prototypes]

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: Idf6d3b4602ba2c7f8313e6335908ce0870f7f89b