soc: rockchip: fiq_debugger: Fix missing prototypes
drivers/soc/rockchip/fiq_debugger/fiq_debugger_arm64.c:45:6: error: no previous prototype for function 'fiq_debugger_dump_regs_aarch32' [-Werror,-Wmissing-prototypes]
drivers/soc/rockchip/fiq_debugger/fiq_debugger_arm64.c:64:6: error: no previous prototype for function 'fiq_debugger_dump_regs_aarch64' [-Werror,-Wmissing-prototypes]

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: Ie44867116113a460c55e6884f51c3671854d7aa2