clk: rockchip: Add missing MODULE_LICENSE()
ERROR: modpost: missing MODULE_LICENSE() in drivers/clk/rockchip/clk-rockchip.o

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I875c24b00995e955056eea03a048d54032085590